import { makeStyles } from "@material-ui/core";

const useStyles = makeStyles((theme) => ({
  main: {
    display: "flex",
    height: "100vh",
    width: "100%",
    background: "linear-gradient(135deg,#FF416C,#203A43,#0F2027)",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    boxSizing: "border-box",
    overflow: "auto",
  },
  appBar: {
    position: "absolute",
    top: "0px",
    right: "0px",
    display: "flex",
    justifyContent: "space-between",
    paddingLeft: "10%",
    paddingRight: "10%",
    [theme.breakpoints.down("xs")]: {
      paddingLeft: "5%",
      paddingRight: "5%",
    },
  },
  profileBtn: {
    border: "2px solid #fff",
    backgroundColor: "white",
    borderRadius: "20px",
    fontFamily: "Roboto",
    color: "black",
    margin: "0.5rem",
    padding: "0.4rem",
    paddingLeft: "0.8rem",
    paddingRight: "0.8rem",
    textDecoration: "none",
    transition: "0.3s",
    "&:hover": {
      border: "2px solid black",
      borderRadius: "20px",
      backgroundColor: "black",
      color: "white",
    },
    [theme.breakpoints.down("xs")]: {
      margin: "0.2rem",
      padding: "0.3rem",
      paddingLeft: "0.5rem",
      paddingRight: "0.5rem",
      fontSize: "0.8rem",
    },
  },
  logoutBtn: {
    border: "2px solid #fff",
    borderRadius: "20px",
    fontFamily: "Roboto",
    color: "white",
    margin: "0.5rem",
    padding: "0.4rem",
    paddingLeft: "0.8rem",
    paddingRight: "0.8rem",
    textDecoration: "none",
    transition: "0.3s",
    "&:hover": {
      backgroundColor: "white",
      color: "black",
    },
    [theme.breakpoints.down("xs")]: {
      margin: "0.2rem",
      padding: "0.3rem",
      paddingLeft: "0.5rem",
      paddingRight: "0.5rem",
      fontSize: "0.8rem",
    },
  },
  title: {
    color: "white",
    fontSize: "10rem",
    fontFamily: "Smooch",
    [theme.breakpoints.down("xs")]: {
      fontSize: "5rem",
    },
  },
  subtitle: {
    color: "white",
    fontSize: "1rem",
    fontFamily: "Montserrat",
    transform: "translateY(-50px)",
    [theme.breakpoints.down("xs")]: {
      fontSize: "0.8rem",
      transform: "translateY(-20px)",
    },
  },
  createLink: {
    backgroundColor: "black",
    color: "white",
    textTransform: "none",
    textDecoration: "none",
    fontSize: "1.1rem",
    fontWeight: "bolder",
    fontFamily: "Poppins",
    letterSpacing: "2px",
    transition: "0.3s",
    padding: "0.5rem",
    borderRadius: "50px",
    "&:hover": {
      background: "white",
      color: "#FF464B",
    },
    [theme.breakpoints.down("xs")]: {
      fontSize: "0.8rem",
    },
  },
}));

export default useStyles;
